# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Profile Readme Development Stats
        # You may pin to the exact commit or the version.
        # uses: anmol098/waka-readme-stats@b2646a9af922f06b6a3cf3c3059e3bb67df077ca
        uses: anmol098/waka-readme-stats@V3
        with:
          # GitHub access token with Repo scope
          GH_TOKEN: ${{ github.token }}
          # Your Wakatime API Key
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          # Show the list of OS Worked on In dev metrics
          SHOW_OS: True
          # Show the list of projects worked on in dev metrics
          SHOW_PROJECTS: True
          # Show the Editors used in dev metrics
          SHOW_EDITORS: True
          # Show the time zone in the dev metrics
          SHOW_TIMEZONE: True
          # Shows the number of commit graph in the dev metrics
          SHOW_COMMIT: True
          # Show the Coding language used in dev metrics
          SHOW_LANGUAGE: False
          # Show the Total Lines of code written Badge till date
          SHOW_LINES_OF_CODE: False
          # Show language or framework used across different repository
          SHOW_LANGUAGE_PER_REPO: True
          SHOW_LOC_CHART: True
          # show day of week you are most productive
          SHOW_DAYS_OF_WEEK: False
          # Shows the current profile views
          SHOW_PROFILE_VIEWS: True
          # Shows the short facts
          SHOW_SHORT_INFO: True

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
